### ISSUE TITLE
As a developer, I want to use NoSQL database to store data and keep it persistent.

### ISSUE THREAD

**Issue by mirahmed39** [nyu-software-engineering/instrument-exchange#18]
### Acceptance Criteria
- [ ] use a remote mysql relational database to store data.
- [ ] do a tutorial on how to connect to a remote mysql db and execute queries.
- [ ] write down schemas
- [ ] do data modeling if possible.

### Estimation of Work:
TBD

**Comment by mirahmed39** [comment]
### Acceptance Criteria
- [ ] use a remote mysql relational database to store data.
- [ ] do a tutorial on how to connect to a remote mysql db and execute queries.
- [ ] write down schemas
- [ ] do data modeling if possible.

### Estimation of Work:
TBD

**Comment by jwanggggg** [comment]
Moving Acceptance Criteria/Work Estimate to description
