### ISSUE TITLE
install and configure react as the front-end framework

### ISSUE THREAD

**Issue by mirahmed39** [nyu-software-engineering/instrument-exchange#26]

**Comment by bloombar** [comment]
@nyu-software-engineering/spring-2019-instrument-exchange - is Alex the the only one who needs to know how to do this?  No!  This is a spike that each team member must do independently. For example, if Alex does this and places this into the Done column of the Sprint 0 Task Board, that would show that the entire team has done this, which would not be accurate. So having only 1 issue for separate pieces of work that need to be independently done by team members is misleading on the Task Board. Please separate this into different issues, each assigned to one team member. Do the same for the other spikes on your task board that need to be done independently by each team member.

**Comment by mirahmed39** [comment]
Got it professor. Will fix this soon!
